import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <footer className="py-6 mt-auto bg-gray-900 border-t border-gray-800 text-center">
          <p className="text-xs text-gray-500 font-medium px-4">
            Desenvolvido por: Pedro Henrique Borges Silva, Alexia Alves, Thiago Leal, David Soares e Valéria Lima.
          </p>
        </footer>
      </body>
    </html>
  );
}
